name: build
on:
  push:

permissions:
    contents: write
    
jobs:
  pandoc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: set permission and run
        run: |
          sudo chmod -R +x . && \
          ./entrypoint.sh
          
      # https://github.com/learnbyexample/learnbyexample.github.io/tree/master/files/pandoc_pdf
      - shell: bash
        run: |
          docker run --rm \
          --entrypoint /data/entrypoint.sh \
          --volume "$(pwd):/data" \
          --user $(id -u):$(id -g) \
          pandoc/latex
          
      - run: ls
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: sample.pdf
