name: build
on:
  push:

permissions:
    contents: write
    
jobs:
  pandoc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - shell: bash
        run: |
          docker run --rm \
          --volume "$(pwd):/data" \
          --user $(id -u):$(id -g) \
          pandoc/latex sample.md --pdf-engine=xelatex -o sample.pdf

      - run: ls
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: sample.pdf
