name: build
on:
  push:
    paths-ignore:
      - '**/README.md'
      
permissions:
    contents: write
    
jobs:
  pandoc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      # https://github.com/learnbyexample/learnbyexample.github.io/tree/master/files/pandoc_pdf
      # docker run must not have -it on GitHub CICD
      - name: set permission and run
        shell: bash
        run: |
          sudo chmod -R +x . && \
          docker run --rm \
          --entrypoint /bin/sh \
          --volume "$(pwd):/data" \
          --user $(id -u):$(id -g) \
          ${{ secrets.DOCKERHUB_USERNAME }}/my-pandoc:202409232032 entrypoint.sh
          
      - run: ls
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: sample.pdf
