name: build
on:
  push:

permissions:
    contents: write
    
jobs:
  pandoc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      # https://github.com/learnbyexample/learnbyexample.github.io/tree/master/files/pandoc_pdf
      - name: set permission and run
        shell: bash
        run: |
          sudo chmod -R +x . && \
          docker build -t my-pandoc . && \
          docker run --rm -it \
          --entrypoint /bin/sh \
          --volume "$(pwd):/data" \
          --user $(id -u):$(id -g) \
          my-pandoc entrypoint.sh
          
      - run: ls
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: sample.pdf
