name: build
on:
  push:

permissions:
    contents: write
    
jobs:
  pandoc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: pandoc/latex
    steps:
      - uses: actions/checkout@v4
      
      - run: pandoc sample.md --pdf-engine=xelatex -o sample.pdf

      - run: ls
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: sample.pdf
