name: ci

on: 
  workflow_dispatch:

permissions:
    contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64 # linux/arm64,
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <-- clone with complete history
          
      - run: |
          docker build --platform linux/amd64 -t "${{ secrets.DOCKERHUB_USERNAME }}/my-pandoc:202409232032" -f ./Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64 # linux/arm64
          tags: '${{ secrets.DOCKERHUB_USERNAME }}/my-pandoc:202409232032'
